package bots;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

import org.openqa.selenium.WebDriver;

import browser.BrowserFunctions;

public class ValidationBot {
	
	public static void generateValidationBotInfo(String name, String email, String password, int amount, String path){
		File file = new File(path);
		
		try{
			file.createNewFile();
			PrintWriter out = new PrintWriter(file);
			String[] splitEmail = email.split("@");
			for(int i = 0; i < amount; i++){
				String newEmail = splitEmail[0] + "+" + Integer.toString(i) + "@" + splitEmail[1];
				out.write(name + "," + newEmail + "," + password + "\n");
			}
			out.close();
		}
		catch(IOException e){
			e.printStackTrace();
		}
	}
	
	/**
	 * This function takes in a string of two numbers, separated by a hyphen ("-"), which will register twitter
	 * accounts with info generated by the generateValidationBotInfo function
	 * @param range - String of two numbers separated by a hyphen
	 */
	public static void registerValidationBots(int start, int end, String path, String emailPassword){
		BufferedReader read;
		try{
			read = new BufferedReader(new FileReader(path));
			if(start > 0){
				int count = 0;
				while(start > count){
					String line = read.readLine();
					count++;
				}
			}
			for(int i = start; i < end; i++){
				String line = read.readLine();
				if(line == null)
					return;
				
				// Pass the email and password for the validation bot into the registerBot function
				String[] botInfo = line.split(",");
				WebDriver driver = BrowserFunctions.registerBot(botInfo[0], botInfo[1], botInfo[2], emailPassword);
				
				Scanner quit = new Scanner(System.in);
				System.out.println("Press any key to close browser");
				String ext = quit.nextLine();
				quit.close();
				driver.close();
				System.out.println("Bot: " + line + " registered, driver closed.");
			}
			read.close();
		}
		catch(IOException e){
			e.printStackTrace();
		}
		
	}
}
